### PR TITLE
initial version of Realtime DataSource

### PR DESCRIPTION
**Pull request by philfleck**
Hi,

this is an initial draft to integrate realtime datasource and some test code. It is based on the `CSVDataSource` and tries to stick to IATK's design prenciple. Please have a look. I am currently cleaning and refactoring some higher layer glue code. Which will follow soon.

let me know,
best philipp

iatk_rtds_1
iatk_rtds_2

### CODE REVIEW

**Comment by atzanteotl** [comment]
Hi Philipp -

This is looking good. A few thoughts for the cleanup:
- IATKRuntime would be better named ReatimeDataDemo or similar.
- RealTimeDataSource can go in the Scripts/Model folder and namespace set to IATK.

I don't think you need to do this for this feature, but in the future I think it would be good for the DataSource to have a simple event emitter so that every time the datasource is updated, associated visualisations can automatically update.

Thanks,
Andrew

**Comment by philfleck** [comment]
Hi,

thanks for the input. I am still new to the internal mechanics of IATK. I will try follow the suggested naming schemes. Since i am still working out some parts of the glue code to a higher layer, the `IATKRuntime` is still subject to change (eg when using it from a javascrict-layer, which i am currently, not all bindings like overloading and reflexion can resolve at runtime).

A reason not having the automatic update in place, is due to realtime data, where one might want to update the view on a different pace as the data comes in.

Since this is not the end, there is more to come (hopefully this week). 
Anyway, thanks for the reply and i will post updates here.

best,
Philipp

**Comment by philfleck** [comment]
Hi,
I just added a reference to PowerUI (only within a README) since i dont know how you want that to be referenced. Additionally,i added sample code and an interface to IATK from js. The js part is executed at runtime without prior knowledge. Maybe it is of interest to keep a brunch with external refs?

However, i have it within a bigger project running with more details and some more code around, which might also be interesting.

Let me know.

best philipp

**Comment by danieljharris** [comment]
@philfleck I've made some recommended changes and submitted a PR to the philfleck:icg_fleck_realtime_datasource branch. Maybe consider making some of the changes so that they can be applied to this PR, let me know if you have any questions 🙂

**Comment by danieljharris** [comment]
Hi @philfleck, thank you for accepting my changes 🙂. I've noticed this PR now includes some code for the Replicator feature you are working on.

I'd recommend removing the Replicator code from this PR and keeping it just for "Replicator for iatk visualizations" PR. We can then keep the features separate and they can then be reviewed separately as well 🙂.

Only a recommendation so up to you, depends on how you want to approach it. Maybe another option would be to combine the two PRs into one maybe?

Thank you again for accepting my changes, really appreciate it!

**Comment by philfleck** [comment]
Hi @danieljharris,

I know, that was my bad, but nothing too big. I am still testing, hopefully i am doe today. I might add some points back which do not work out. There some issue with function overloading, because i am interfacing IATK directly from bindings to JS and not all function overloads are distinguishable and therefore might not be found at runtime. Anyway, this was good progress and i am going to sort out the replicator stuff from this PR, to have it by its own.

best,
Philipp

**Comment by danieljharris** [comment]
Hi @philfleck, yeah that sounds good. I wasn't considering how the function overloading would work with JS so apologies if that didn't work out.

Feel free to add anything back that I changed, my alterations were only suggestions 🙂.

**Comment by philfleck** [comment]
Closed in favor  https://github.com/MaximeCordeil/IATK/pull/22.

**Pull request closed without merging**
