### PR TITLE
Upgraded to Unity 2021.3.2f1 LTS

### PR DESCRIPTION
**Pull request by danieljharris**
Just a basic PR to update IATK to the latest Unity LTS version.
Tested with all visualisations and linked visualisations.

Please let me know if the PR needs any alterations 🙂

List of changes:
- Updated packages
- Updated "CreatePrefab" to use the new "SaveAsPrefabAsset"
- Removed now obsolete "Text Container" (from prefabs and Axis.cs)
- Removed now obsolete "Canvas Renderer" (from prefabs)
- Added "Mapbox", "UserSettings", error logs, and "Serialized Fields" to git ignore
- Updated Readme with new version (2021.3.2f1)

### CODE REVIEW

**Comment by philfleck** [comment]
Hi,
is it still compatible with 2019.4 lts?

**Comment by danieljharris** [comment]
> Hi,
> is it still compatible with 2019.4 lts?

Hi 🙂

I just did some tests and unfortunately this upgrade does not seem to be backwards compatible with 2019.4 LTS. Though it does seem possible to be converted back to 2019 by reverting the packages (Unity editor: Window > Package Manager > Advanced > Reset Packages to defaults) but this is not recommended.

Is there any particular reason you would want to stay on 2019? If you are concerned with library support, I'm more than happy to test my PR with different libraries to check their compatibility 🙂

**Comment by philfleck** [comment]
Thx for the reply. I asked becausee i am still running on 2019.4 and since we use IAKT as part of bigger system with multiple dependencies, i have to carefully update stuff to newer unity releases. But it is a point on my list. :)

**Comment by Permiek** [comment]
Thx for your efforts Daniel.

I cant find the Unity version you list on https://unity3d.com/unity/qa/lts-releases the highest listed is 2020.3.14f1.

Thanks

**Comment by Permiek** [comment]
Thx for your efforts Daniel. I couldnt find 2020.3.15f1 LTS install so am going with 2020.3.14f1 LTS.

**Comment by danieljharris** [comment]
> Thx for your efforts Daniel. I couldnt find 2020.3.15f1 LTS install so am going with 2020.3.14f1 LTS.

Yeah it should work just as well with 2020.3.14f1 🙂

But let me know if you have any issues with it

**Pull request merged**
